// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: listener/v1/listener.proto

package listenerv1

import (
	v1 "github.com/kdubbo/xds-api/core/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiListener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiListener   *anypb.Any             `protobuf:"bytes,1,opt,name=api_listener,json=apiListener,proto3" json:"api_listener,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiListener) Reset() {
	*x = ApiListener{}
	mi := &file_listener_v1_listener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiListener) ProtoMessage() {}

func (x *ApiListener) ProtoReflect() protoreflect.Message {
	mi := &file_listener_v1_listener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiListener.ProtoReflect.Descriptor instead.
func (*ApiListener) Descriptor() ([]byte, []int) {
	return file_listener_v1_listener_proto_rawDescGZIP(), []int{0}
}

func (x *ApiListener) GetApiListener() *anypb.Any {
	if x != nil {
		return x.ApiListener
	}
	return nil
}

type AdditionalAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *v1.Address            `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdditionalAddress) Reset() {
	*x = AdditionalAddress{}
	mi := &file_listener_v1_listener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdditionalAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalAddress) ProtoMessage() {}

func (x *AdditionalAddress) ProtoReflect() protoreflect.Message {
	mi := &file_listener_v1_listener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalAddress.ProtoReflect.Descriptor instead.
func (*AdditionalAddress) Descriptor() ([]byte, []int) {
	return file_listener_v1_listener_proto_rawDescGZIP(), []int{1}
}

func (x *AdditionalAddress) GetAddress() *v1.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Listener struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address             *v1.Address            `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	AdditionalAddresses []*AdditionalAddress   `protobuf:"bytes,33,rep,name=additional_addresses,json=additionalAddresses,proto3" json:"additional_addresses,omitempty"`
	FilterChains        []*FilterChain         `protobuf:"bytes,3,rep,name=filter_chains,json=filterChains,proto3" json:"filter_chains,omitempty"`
	ApiListener         *ApiListener           `protobuf:"bytes,19,opt,name=api_listener,json=apiListener,proto3" json:"api_listener,omitempty"`
	ListenerFilters     []*anypb.Any           `protobuf:"bytes,9,rep,name=listener_filters,json=listenerFilters,proto3" json:"listener_filters,omitempty"`
	UseOriginalDst      *wrapperspb.BoolValue  `protobuf:"bytes,12,opt,name=use_original_dst,json=useOriginalDst,proto3" json:"use_original_dst,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Listener) Reset() {
	*x = Listener{}
	mi := &file_listener_v1_listener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_listener_v1_listener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_listener_v1_listener_proto_rawDescGZIP(), []int{2}
}

func (x *Listener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listener) GetAddress() *v1.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Listener) GetAdditionalAddresses() []*AdditionalAddress {
	if x != nil {
		return x.AdditionalAddresses
	}
	return nil
}

func (x *Listener) GetFilterChains() []*FilterChain {
	if x != nil {
		return x.FilterChains
	}
	return nil
}

func (x *Listener) GetApiListener() *ApiListener {
	if x != nil {
		return x.ApiListener
	}
	return nil
}

func (x *Listener) GetListenerFilters() []*anypb.Any {
	if x != nil {
		return x.ListenerFilters
	}
	return nil
}

func (x *Listener) GetUseOriginalDst() *wrapperspb.BoolValue {
	if x != nil {
		return x.UseOriginalDst
	}
	return nil
}

var File_listener_v1_listener_proto protoreflect.FileDescriptor

const file_listener_v1_listener_proto_rawDesc = "" +
	"\n" +
	"\x1alistener/v1/listener.proto\x12\vlistener.v1\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x15core/v1/address.proto\x1a%listener/v1/listener_components.proto\"F\n" +
	"\vApiListener\x127\n" +
	"\fapi_listener\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\vapiListener\"?\n" +
	"\x11AdditionalAddress\x12*\n" +
	"\aaddress\x18\x01 \x01(\v2\x10.core.v1.AddressR\aaddress\"\xa0\x03\n" +
	"\bListener\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\aaddress\x18\x02 \x01(\v2\x10.core.v1.AddressR\aaddress\x12Q\n" +
	"\x14additional_addresses\x18! \x03(\v2\x1e.listener.v1.AdditionalAddressR\x13additionalAddresses\x12=\n" +
	"\rfilter_chains\x18\x03 \x03(\v2\x18.listener.v1.FilterChainR\ffilterChains\x12;\n" +
	"\fapi_listener\x18\x13 \x01(\v2\x18.listener.v1.ApiListenerR\vapiListener\x12?\n" +
	"\x10listener_filters\x18\t \x03(\v2\x14.google.protobuf.AnyR\x0flistenerFilters\x12D\n" +
	"\x10use_original_dst\x18\f \x01(\v2\x1a.google.protobuf.BoolValueR\x0euseOriginalDstB2Z0github.com/kdubbo/xds-api/listener/v1;listenerv1b\x06proto3"

var (
	file_listener_v1_listener_proto_rawDescOnce sync.Once
	file_listener_v1_listener_proto_rawDescData []byte
)

func file_listener_v1_listener_proto_rawDescGZIP() []byte {
	file_listener_v1_listener_proto_rawDescOnce.Do(func() {
		file_listener_v1_listener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listener_v1_listener_proto_rawDesc), len(file_listener_v1_listener_proto_rawDesc)))
	})
	return file_listener_v1_listener_proto_rawDescData
}

var file_listener_v1_listener_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_listener_v1_listener_proto_goTypes = []any{
	(*ApiListener)(nil),          // 0: listener.v1.ApiListener
	(*AdditionalAddress)(nil),    // 1: listener.v1.AdditionalAddress
	(*Listener)(nil),             // 2: listener.v1.Listener
	(*anypb.Any)(nil),            // 3: google.protobuf.Any
	(*v1.Address)(nil),           // 4: core.v1.Address
	(*FilterChain)(nil),          // 5: listener.v1.FilterChain
	(*wrapperspb.BoolValue)(nil), // 6: google.protobuf.BoolValue
}
var file_listener_v1_listener_proto_depIdxs = []int32{
	3, // 0: listener.v1.ApiListener.api_listener:type_name -> google.protobuf.Any
	4, // 1: listener.v1.AdditionalAddress.address:type_name -> core.v1.Address
	4, // 2: listener.v1.Listener.address:type_name -> core.v1.Address
	1, // 3: listener.v1.Listener.additional_addresses:type_name -> listener.v1.AdditionalAddress
	5, // 4: listener.v1.Listener.filter_chains:type_name -> listener.v1.FilterChain
	0, // 5: listener.v1.Listener.api_listener:type_name -> listener.v1.ApiListener
	3, // 6: listener.v1.Listener.listener_filters:type_name -> google.protobuf.Any
	6, // 7: listener.v1.Listener.use_original_dst:type_name -> google.protobuf.BoolValue
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_listener_v1_listener_proto_init() }
func file_listener_v1_listener_proto_init() {
	if File_listener_v1_listener_proto != nil {
		return
	}
	file_listener_v1_listener_components_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listener_v1_listener_proto_rawDesc), len(file_listener_v1_listener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listener_v1_listener_proto_goTypes,
		DependencyIndexes: file_listener_v1_listener_proto_depIdxs,
		MessageInfos:      file_listener_v1_listener_proto_msgTypes,
	}.Build()
	File_listener_v1_listener_proto = out.File
	file_listener_v1_listener_proto_goTypes = nil
	file_listener_v1_listener_proto_depIdxs = nil
}
