syntax = "proto3";

package extensions.filters.http.ext_authz.v1;

import "google/protobuf/duration.proto";
import "extensions/filters/v1/http/rbac/rbac.proto";

option go_package = "github.com/kdubbo/xds-api/extensions/filters/v1/http/ext_authz;ext_authzv1";

message ExtAuthz {
  enum Protocol {
    HTTP = 0;
    GRPC = 1;
  }

  string provider = 1;
  Protocol protocol = 2;
  string service = 3;
  uint32 port = 4;
  string path_prefix = 5;
  repeated string include_request_headers_in_check = 6;
  repeated string headers_to_upstream_on_allow = 7;
  repeated string headers_to_downstream_on_deny = 8;
  google.protobuf.Duration timeout = 9;
  bool fail_open = 10;
  bool shadow = 11;
  repeated extensions.filters.http.rbac.v1.Rule rules = 12;
}
